// Package e2e implements docs/EXPERIMENT.md's E2 scenarios S1-S7 in-process:
// no CometBFT node, no Docker, no real partitioning. Harness.Advance() drives
// the real BeginBlocker against mock BTC/DA/P2P sensors, so the FSM logic
// under test is the exact code path a running chain uses -- only the
// peripheral I/O is mocked.
//
// Produces real data for E2's FSM-behavior metrics (time-to-fallback,
// recovery time, withdrawal-blocked count, flapping count), which are pure
// functions of the (height, state, sensor) timeline -- a real Docker/Pumba
// testnet is out of scope for this harness.
package e2e

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/keeper/sensors"
	"github.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/types"
	"github.com/stretchr/testify/require"
)

const summaryPath = "results/e2_summary.md"

func TestMain(m *testing.M) {
	_ = os.MkdirAll("results", 0o755)
	f, err := os.Create(summaryPath)
	if err == nil {
		_, _ = f.WriteString("# E2 Fault-Injection Results\n\n")
		_, _ = f.WriteString("Generated by `go test ./tests/e2e/...` -- tests/e2e/harness.go drives x/sovereignty's\n")
		_, _ = f.WriteString("real BeginBlocker in-process against mock BTC/DA/P2P sensors (no CometBFT node, no Docker).\n\n")
		_, _ = f.WriteString("| Scenario | time_to_detection | time_to_fallback | recovery_time | withdrawal_blocked_blocks | flapping_count | total_transitions |\n")
		_, _ = f.WriteString("|---|---:|---:|---:|---:|---:|---:|\n")
		f.Close()
	}
	os.Exit(m.Run())
}

func appendSummaryRow(name string, m E2Metrics) {
	f, err := os.OpenFile(summaryPath, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	_, _ = f.WriteString(
		"| " + name +
			" | " + itoa64(m.TimeToDetection) +
			" | " + itoa64(m.TimeToFallback) +
			" | " + itoa64(m.RecoveryTime) +
			" | " + itoa(m.WithdrawalBlocked) +
			" | " + itoa(m.FlappingCount) +
			" | " + itoa(m.TotalTransitions) +
			" |\n")
}

func itoa64(v int64) string { return itoa(int(v)) }
func itoa(v int) string {
	if v < 0 {
		return "n/a"
	}
	// small, dependency-free int->string (avoids pulling in strconv just for this)
	if v == 0 {
		return "0"
	}
	neg := false
	if v < 0 {
		neg = true
		v = -v
	}
	var buf [20]byte
	i := len(buf)
	for v > 0 {
		i--
		buf[i] = byte('0' + v%10)
		v /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}

// S1 -- Normal: all sensors healthy throughout; must stay ANCHORED for the
// whole run (E2's failure-matrix baseline row).
func TestE2_S1_Normal(t *testing.T) {
	h := NewHarness(t)
	for height := 0; height < 50; height++ {
		h.Advance()
	}

	for _, row := range h.Timeline() {
		require.Equal(t, types.StateAnchored, row.State, "height %d: S1 must stay ANCHORED under all-healthy sensors", row.Height)
		require.False(t, row.WithdrawLocked, "height %d: withdrawals must not be locked in ANCHORED", row.Height)
	}

	m := h.ComputeMetrics()
	h.WriteCSV("s1_normal")
	appendSummaryRow("S1 Normal", m)
	t.Log(fmtMetrics("S1", m))
}

// S2 -- BTC congestion: btc_gap ramps past SOVEREIGN_THRESHOLD then heals.
// Expect ANCHORED -> SUSPICIOUS -> SOVEREIGN -> RECOVERING -> ANCHORED, and
// the chain never stops producing blocks throughout the outage.
func TestE2_S2_BTCCongestion(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	// Ramp: 0, cross SuspiciousThreshold, sit at SovereignThreshold -- derived
	// from p's real thresholds, not hardcoded.
	h.BTC.SetGap(0)
	h.Advance()
	h.BTC.SetGap(p.SuspiciousThreshold)
	h.Advance()
	h.BTC.SetGap(p.SovereignThreshold)
	for i := 0; i < 4; i++ {
		h.Advance()
	}
	require.Equal(t, types.StateSovereign, h.State(), "sustained btc_gap >= SOVEREIGN_THRESHOLD must reach SOVEREIGN")

	// Heal: gap back to 0, hold long enough to satisfy HysteresisWait, submit proof.
	h.BTC.SetGap(0)
	for i := uint64(0); i <= p.HysteresisWait+2; i++ {
		if i == 1 {
			h.SetReanchoringProofValid(true)
		}
		h.Advance()
	}
	require.Equal(t, types.StateAnchored, h.State(), "S2 must fully recover to ANCHORED once btc_gap heals and hysteresis+proof are satisfied")

	m := h.ComputeMetrics()
	require.NotEqual(t, int64(-1), m.TimeToFallback, "S2 must record a real time-to-fallback")
	require.NotEqual(t, int64(-1), m.RecoveryTime, "S2 must record a real recovery time")
	h.WriteCSV("s2_btc_congestion")
	appendSummaryRow("S2 BTC congestion", m)
	t.Log(fmtMetrics("S2", m))
}

// S3 -- DA unavailable: a DA receipt alone is only a warning (IsCriticalCondition
// has no DA disjunct), so SOVEREIGN only comes via the gray-failure timeout
// (suspicious_duration >= MaxSuspiciousTime) if the outage persists.
func TestE2_S3_DAUnavailable(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	h.DA.SetAvailable(false)
	for i := uint64(0); i < p.MaxSuspiciousTime+3; i++ {
		h.Advance()
	}
	// DefaultParams has MaxSuspiciousTime=1 -- a persistent DA outage must
	// escalate via gray-failure timeout, not hang in SUSPICIOUS.
	require.Equal(t, types.StateSovereign, h.State(), "persistent DA outage must eventually escalate via gray-failure timeout")

	h.DA.SetAvailable(true)
	for i := uint64(0); i <= p.HysteresisWait+2; i++ {
		if i == 1 {
			h.SetReanchoringProofValid(true)
		}
		h.Advance()
	}
	require.Equal(t, types.StateAnchored, h.State())

	m := h.ComputeMetrics()
	h.WriteCSV("s3_da_unavailable")
	appendSummaryRow("S3 DA unavailable", m)
	t.Log(fmtMetrics("S3", m))
}

// S4 -- P2P eclipse (partial): diversity/clean-peers drop below thresholds
// but an anchor peer remains (not full isolation). Expect SUSPICIOUS after
// DownHysteresisThreshold recurrences (E5's flapping fix absorbs short blips),
// not an immediate SOVEREIGN -- unless the gray-failure timeout fires.
func TestE2_S4_P2PEclipsePartial(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	h.P2P.SetSnapshot(sensors.P2PSnapshot{
		ActiveAnchors:   p.MinAnchorPeers, // still >=1: not a total isolation
		CleanPeers:      0,                // below MinPeers -> unhealthy
		SubnetDiversity: 0,                // below MinSubnetDiversity -> unhealthy
		ChurnRate:       p.MaxChurnRate + 5,
		AvgTenure:       0,
		Latency:         p.MaxPeerLatency + 5,
	})
	for i := uint64(0); i < p.DownHysteresisThreshold; i++ {
		h.Advance()
	}
	require.Equal(t, types.StateSuspicious, h.State(), "a sustained partial eclipse (anchors still present) must eventually warn, not immediately fall back")

	for i := uint64(0); i < p.MaxSuspiciousTime+2; i++ {
		h.Advance()
	}
	require.Equal(t, types.StateSovereign, h.State(), "a sustained partial eclipse must still escalate via gray-failure timeout")

	m := h.ComputeMetrics()
	h.WriteCSV("s4_p2p_eclipse_partial")
	appendSummaryRow("S4 P2P eclipse partial", m)
	t.Log(fmtMetrics("S4", m))
}

// S5 -- Anchor isolation: ActiveAnchors hits 0 (complete anchor eclipse).
// Expect an immediate jump to SOVEREIGN per IsCriticalCondition's
// Cardinality(ActiveAnchors)=0 disjunct.
func TestE2_S5_AnchorIsolation(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	h.Advance() // one healthy block first, so the transition is clearly on-isolation
	require.Equal(t, types.StateAnchored, h.State())

	h.P2P.SetSnapshot(sensors.P2PSnapshot{
		ActiveAnchors:   0,
		CleanPeers:      p.MinPeers,
		SubnetDiversity: p.MinSubnetDiversity,
		AvgTenure:       p.MinAvgTenure,
	})
	h.Advance()
	require.Equal(t, types.StateSovereign, h.State(), "total anchor-peer loss must force SOVEREIGN immediately (IsCriticalCondition)")

	m := h.ComputeMetrics()
	require.Equal(t, int64(2), m.TimeToFallback, "isolation must trigger fallback on the very next block")
	h.WriteCSV("s5_anchor_isolation")
	appendSummaryRow("S5 Anchor isolation", m)
	t.Log(fmtMetrics("S5", m))
}

// S6 -- Combined BTC+DA failure: both peripherals down at once. Expect
// SOVEREIGN (BTC critical branch) with withdrawals locked for the entire
// outage (chain still processes local txs).
func TestE2_S6_CombinedBTCAndDAFailure(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	h.BTC.SetGap(p.SovereignThreshold)
	h.DA.SetAvailable(false)
	for i := 0; i < 10; i++ {
		h.Advance()
	}

	for _, row := range h.Timeline() {
		require.Equal(t, types.StateSovereign, row.State, "height %d: combined BTC+DA failure must stay SOVEREIGN", row.Height)
		require.True(t, row.WithdrawLocked, "height %d: withdrawals must be locked throughout the combined outage", row.Height)
	}

	m := h.ComputeMetrics()
	require.Equal(t, len(h.Timeline()), m.WithdrawalBlocked, "every block in this scenario must have withdrawals locked")
	h.WriteCSV("s6_combined_btc_da_failure")
	appendSummaryRow("S6 Combined BTC+DA failure", m)
	t.Log(fmtMetrics("S6", m))
}

// S7 -- Recovery: sensors heal and a valid reanchoring proof is submitted.
// Expect SOVEREIGN -> RECOVERING -> ANCHORED only once BOTH hysteresis AND
// the proof are satisfied -- not before.
func TestE2_S7_Recovery(t *testing.T) {
	h := NewHarness(t)
	p := types.DefaultParams()

	h.BTC.SetGap(p.SovereignThreshold)
	h.Advance()
	require.Equal(t, types.StateSovereign, h.State())

	h.BTC.SetGap(0)
	h.Advance()
	require.Equal(t, types.StateRecovering, h.State(), "healed sensors must move SOVEREIGN -> RECOVERING")

	// Hold in RECOVERING without a valid proof -- must not exit early even
	// once safe_blocks reaches HysteresisWait.
	for i := uint64(0); i < p.HysteresisWait; i++ {
		h.Advance()
	}
	require.Equal(t, types.StateRecovering, h.State(), "must not exit RECOVERING before the reanchoring proof is submitted, even with hysteresis satisfied")

	h.SetReanchoringProofValid(true)
	h.Advance()
	require.Equal(t, types.StateAnchored, h.State(), "RECOVERING -> ANCHORED once both hysteresis and proof are satisfied")

	m := h.ComputeMetrics()
	require.NotEqual(t, int64(-1), m.RecoveryTime, "S7 must record a real recovery time")
	filepathCSV := h.WriteCSV("s7_recovery")
	appendSummaryRow("S7 Recovery", m)
	t.Logf("%s (csv: %s)", fmtMetrics("S7", m), filepath.Base(filepathCSV))
}
