package keeper

import (
	"bytes"
	"context"
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"
)

// embeddedVK is the verification key for circuit/reanchoring/src/main.nr's
// compiled N=4 circuit (circuit/reanchoring/target/proof/vk, generated by
// `bb write_vk`, see scripts/e6_zk_reanchoring_benchmark/benchmark_prover.sh).
// Copied here rather than embedded directly from circuit/reanchoring/target/
// (gitignored, and outside this package's directory tree -- go:embed cannot
// reach outside its own package via `..`), so every validator ships the
// exact same VK regardless of whether it has ever run nargo/bb locally. If
// the circuit is ever recompiled (different N, changed constraints), this
// file MUST be replaced with the new `bb write_vk` output by hand -- there
// is no automated sync between the two copies.
//
//go:embed zk_assets/vk
var embeddedVK []byte

// bbBinary is the pinned bb (Barretenberg) CLI used for verification -- see
// VerifyZKProof's doc for why every validator must run the SAME bb build.
const bbBinary = "bb"

// VerifyZKProof shells out to `bb verify` against the circuit's embedded
// verification key -- the "Verify" side of spec/README.md's §Re-anchoring
// via ZK-Proof of Recovery, and this repo's real Noir/Barretenberg
// counterpart of spec/core/EngramTendermint.tla's VerifyZkProof (that
// operator is a deliberate "black-box O(1) simulation" at the abstract
// consensus-hot-path level -- x/sovereignty/proposal.go's verifyZkProofFlag
// already implements THAT faithfully; this function backs the SEPARATE,
// concrete MsgSubmitRecoveryProofRequest path, where a real proof actually
// gets checked).
//
// This runs inside DeliverTx (via MsgServerImpl.SubmitRecoveryProof),
// executed identically by every validator -- for that to stay
// consensus-safe, `bb verify`'s result must be a pure, deterministic
// function of (vk, proof, inputs) on every validator's machine. That
// requires every validator to run the SAME bb build: pin an exact bb
// release (not a floating nightly) across all validators, checked loudly at
// `engramd start`, not silently discovered per-tx.
//
// Fails closed (returns false, never panics) if bb is missing, times out, or
// exits non-zero -- a misconfigured validator should reject the proof, not
// silently accept it.
func (k *Keeper) VerifyZKProof(proof []byte, inputs []byte) bool {
	dir, err := os.MkdirTemp("", "engram-zkverify-*")
	if err != nil {
		fmt.Println("engramd: ZK proof verification failed to allocate temp dir:", err)
		return false
	}
	defer os.RemoveAll(dir)

	vkPath := filepath.Join(dir, "vk")
	proofPath := filepath.Join(dir, "proof")
	inputsPath := filepath.Join(dir, "public_inputs")
	if err := os.WriteFile(vkPath, embeddedVK, 0o600); err != nil {
		fmt.Println("engramd: ZK proof verification failed writing vk:", err)
		return false
	}
	if err := os.WriteFile(proofPath, proof, 0o600); err != nil {
		fmt.Println("engramd: ZK proof verification failed writing proof:", err)
		return false
	}
	if err := os.WriteFile(inputsPath, inputs, 0o600); err != nil {
		fmt.Println("engramd: ZK proof verification failed writing public_inputs:", err)
		return false
	}

	// E6's own measured verify_s at N=4 is ~20ms
	// (scripts/e6_zk_reanchoring_benchmark/results/table6b_scaling.csv) --
	// 10s leaves enormous headroom purely as a hang safety-valve, not a
	// tight bound that would itself introduce cross-validator
	// nondeterminism from hardware-speed variance.
	execCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cmd := exec.CommandContext(execCtx, bbBinary, "verify", "-k", vkPath, "-p", proofPath, "-i", inputsPath)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		fmt.Printf("engramd: ZK proof verification rejected: %v: %s\n", err, stderr.String())
		return false
	}
	return true
}
