// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engram/sovereignty/v1/genesis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu trúc khởi tạo máy trạng thái Engram FSM. fsm_state là string (không phải
// enum) để khớp đúng biểu diễn "ANCHORED"/"SUSPICIOUS"/"SOVEREIGN"/"RECOVERING"
// trong spec/core/EngramFSM.tla (state \in {"ANCHORED", ...}) và trong
// x/sovereignty/types/state.go's StateAnchored/... constants.
type GenesisState struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FsmState              string                 `protobuf:"bytes,1,opt,name=fsm_state,json=fsmState,proto3" json:"fsm_state,omitempty"`                                           // Thường khởi tạo là "ANCHORED"
	SafeBlocksCounter     uint64                 `protobuf:"varint,2,opt,name=safe_blocks_counter,json=safeBlocksCounter,proto3" json:"safe_blocks_counter,omitempty"`             // Bộ đếm biến `safe_blocks` trong TLA+
	SuspiciousDuration    uint64                 `protobuf:"varint,3,opt,name=suspicious_duration,json=suspiciousDuration,proto3" json:"suspicious_duration,omitempty"`            // Bộ đếm biến `suspicious_duration` trong TLA+
	ReanchoringProofValid bool                   `protobuf:"varint,4,opt,name=reanchoring_proof_valid,json=reanchoringProofValid,proto3" json:"reanchoring_proof_valid,omitempty"` // Biến `reanchoring_proof_valid` trong TLA+
	HysteresisWaitLimit   uint64                 `protobuf:"varint,5,opt,name=hysteresis_wait_limit,json=hysteresisWaitLimit,proto3" json:"hysteresis_wait_limit,omitempty"`       // Tham số hệ thống giới hạn HYSTERESIS_WAIT
	InitialMetrics        *PeripheralMetrics     `protobuf:"bytes,6,opt,name=initial_metrics,json=initialMetrics,proto3" json:"initial_metrics,omitempty"`                         // Trạng thái sensor lúc khởi tạo
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetFsmState() string {
	if x != nil {
		return x.FsmState
	}
	return ""
}

func (x *GenesisState) GetSafeBlocksCounter() uint64 {
	if x != nil {
		return x.SafeBlocksCounter
	}
	return 0
}

func (x *GenesisState) GetSuspiciousDuration() uint64 {
	if x != nil {
		return x.SuspiciousDuration
	}
	return 0
}

func (x *GenesisState) GetReanchoringProofValid() bool {
	if x != nil {
		return x.ReanchoringProofValid
	}
	return false
}

func (x *GenesisState) GetHysteresisWaitLimit() uint64 {
	if x != nil {
		return x.HysteresisWaitLimit
	}
	return 0
}

func (x *GenesisState) GetInitialMetrics() *PeripheralMetrics {
	if x != nil {
		return x.InitialMetrics
	}
	return nil
}

var File_engram_sovereignty_v1_genesis_proto protoreflect.FileDescriptor

const file_engram_sovereignty_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"#engram/sovereignty/v1/genesis.proto\x12\x15engram.sovereignty.v1\x1a!engram/sovereignty/v1/state.proto\"\xcb\x02\n" +
	"\fGenesisState\x12\x1b\n" +
	"\tfsm_state\x18\x01 \x01(\tR\bfsmState\x12.\n" +
	"\x13safe_blocks_counter\x18\x02 \x01(\x04R\x11safeBlocksCounter\x12/\n" +
	"\x13suspicious_duration\x18\x03 \x01(\x04R\x12suspiciousDuration\x126\n" +
	"\x17reanchoring_proof_valid\x18\x04 \x01(\bR\x15reanchoringProofValid\x122\n" +
	"\x15hysteresis_wait_limit\x18\x05 \x01(\x04R\x13hysteresisWaitLimit\x12Q\n" +
	"\x0finitial_metrics\x18\x06 \x01(\v2(.engram.sovereignty.v1.PeripheralMetricsR\x0einitialMetricsBCZAgithub.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/typesb\x06proto3"

var (
	file_engram_sovereignty_v1_genesis_proto_rawDescOnce sync.Once
	file_engram_sovereignty_v1_genesis_proto_rawDescData []byte
)

func file_engram_sovereignty_v1_genesis_proto_rawDescGZIP() []byte {
	file_engram_sovereignty_v1_genesis_proto_rawDescOnce.Do(func() {
		file_engram_sovereignty_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_genesis_proto_rawDesc), len(file_engram_sovereignty_v1_genesis_proto_rawDesc)))
	})
	return file_engram_sovereignty_v1_genesis_proto_rawDescData
}

var file_engram_sovereignty_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engram_sovereignty_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil),      // 0: engram.sovereignty.v1.GenesisState
	(*PeripheralMetrics)(nil), // 1: engram.sovereignty.v1.PeripheralMetrics
}
var file_engram_sovereignty_v1_genesis_proto_depIdxs = []int32{
	1, // 0: engram.sovereignty.v1.GenesisState.initial_metrics:type_name -> engram.sovereignty.v1.PeripheralMetrics
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engram_sovereignty_v1_genesis_proto_init() }
func file_engram_sovereignty_v1_genesis_proto_init() {
	if File_engram_sovereignty_v1_genesis_proto != nil {
		return
	}
	file_engram_sovereignty_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_genesis_proto_rawDesc), len(file_engram_sovereignty_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engram_sovereignty_v1_genesis_proto_goTypes,
		DependencyIndexes: file_engram_sovereignty_v1_genesis_proto_depIdxs,
		MessageInfos:      file_engram_sovereignty_v1_genesis_proto_msgTypes,
	}.Build()
	File_engram_sovereignty_v1_genesis_proto = out.File
	file_engram_sovereignty_v1_genesis_proto_goTypes = nil
	file_engram_sovereignty_v1_genesis_proto_depIdxs = nil
}
