// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engram/sovereignty/v1/genesis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Initial Engram FSM state. fsm_state is a string to match the
// "ANCHORED"/"SUSPICIOUS"/"SOVEREIGN"/"RECOVERING" literals of
// spec/core/EngramFSM.tla and x/sovereignty/types/state.go.
type GenesisState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FsmState               string                 `protobuf:"bytes,1,opt,name=fsm_state,json=fsmState,proto3" json:"fsm_state,omitempty"`                                              // Usually "ANCHORED" at genesis
	SafeBlocksCounter      uint64                 `protobuf:"varint,2,opt,name=safe_blocks_counter,json=safeBlocksCounter,proto3" json:"safe_blocks_counter,omitempty"`                // Counter for TLA+ `safe_blocks`
	SuspiciousDuration     uint64                 `protobuf:"varint,3,opt,name=suspicious_duration,json=suspiciousDuration,proto3" json:"suspicious_duration,omitempty"`               // Counter for TLA+ `suspicious_duration`
	ReanchoringProofValid  bool                   `protobuf:"varint,4,opt,name=reanchoring_proof_valid,json=reanchoringProofValid,proto3" json:"reanchoring_proof_valid,omitempty"`    // TLA+ `reanchoring_proof_valid`
	InitialMetrics         *PeripheralMetrics     `protobuf:"bytes,6,opt,name=initial_metrics,json=initialMetrics,proto3" json:"initial_metrics,omitempty"`                            // Initial sensor snapshot
	Params                 *GenesisParams         `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`                                                                  // Operational params, see GenesisParams
	UnhealthyStreak        uint64                 `protobuf:"varint,8,opt,name=unhealthy_streak,json=unhealthyStreak,proto3" json:"unhealthy_streak,omitempty"`                        // TLA+ `unhealthy_streak` (down-hysteresis)
	FailedRecoveryAttempts uint64                 `protobuf:"varint,9,opt,name=failed_recovery_attempts,json=failedRecoveryAttempts,proto3" json:"failed_recovery_attempts,omitempty"` // TLA+ `failed_recovery_attempts` (exponential backoff)
	SuspiciousSafeBlocks   uint64                 `protobuf:"varint,10,opt,name=suspicious_safe_blocks,json=suspiciousSafeBlocks,proto3" json:"suspicious_safe_blocks,omitempty"`      // TLA+ `suspicious_safe_blocks` (SUSPICIOUS exit hysteresis)
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetFsmState() string {
	if x != nil {
		return x.FsmState
	}
	return ""
}

func (x *GenesisState) GetSafeBlocksCounter() uint64 {
	if x != nil {
		return x.SafeBlocksCounter
	}
	return 0
}

func (x *GenesisState) GetSuspiciousDuration() uint64 {
	if x != nil {
		return x.SuspiciousDuration
	}
	return 0
}

func (x *GenesisState) GetReanchoringProofValid() bool {
	if x != nil {
		return x.ReanchoringProofValid
	}
	return false
}

func (x *GenesisState) GetInitialMetrics() *PeripheralMetrics {
	if x != nil {
		return x.InitialMetrics
	}
	return nil
}

func (x *GenesisState) GetParams() *GenesisParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetUnhealthyStreak() uint64 {
	if x != nil {
		return x.UnhealthyStreak
	}
	return 0
}

func (x *GenesisState) GetFailedRecoveryAttempts() uint64 {
	if x != nil {
		return x.FailedRecoveryAttempts
	}
	return 0
}

func (x *GenesisState) GetSuspiciousSafeBlocks() uint64 {
	if x != nil {
		return x.SuspiciousSafeBlocks
	}
	return 0
}

// GenesisParams mirrors types.Params (x/sovereignty/types/params.go) for
// genesis-time config. genesis.json is generated once and copied identically
// to all nodes, so values are uniform across the validator set.
type GenesisParams struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SuspiciousThreshold        uint64                 `protobuf:"varint,1,opt,name=suspicious_threshold,json=suspiciousThreshold,proto3" json:"suspicious_threshold,omitempty"`
	SovereignThreshold         uint64                 `protobuf:"varint,2,opt,name=sovereign_threshold,json=sovereignThreshold,proto3" json:"sovereign_threshold,omitempty"`
	DaThreshold                uint64                 `protobuf:"varint,3,opt,name=da_threshold,json=daThreshold,proto3" json:"da_threshold,omitempty"`
	HysteresisWait             uint64                 `protobuf:"varint,4,opt,name=hysteresis_wait,json=hysteresisWait,proto3" json:"hysteresis_wait,omitempty"`
	MinPeers                   uint64                 `protobuf:"varint,5,opt,name=min_peers,json=minPeers,proto3" json:"min_peers,omitempty"`
	MinSubnetDiversity         uint64                 `protobuf:"varint,6,opt,name=min_subnet_diversity,json=minSubnetDiversity,proto3" json:"min_subnet_diversity,omitempty"`
	MinAnchorPeers             uint64                 `protobuf:"varint,7,opt,name=min_anchor_peers,json=minAnchorPeers,proto3" json:"min_anchor_peers,omitempty"`
	MaxChurnRate               uint64                 `protobuf:"varint,8,opt,name=max_churn_rate,json=maxChurnRate,proto3" json:"max_churn_rate,omitempty"`
	MinAvgTenure               uint64                 `protobuf:"varint,9,opt,name=min_avg_tenure,json=minAvgTenure,proto3" json:"min_avg_tenure,omitempty"`
	MaxPeerLatency             uint64                 `protobuf:"varint,10,opt,name=max_peer_latency,json=maxPeerLatency,proto3" json:"max_peer_latency,omitempty"`
	MaxSuspiciousTime          uint64                 `protobuf:"varint,11,opt,name=max_suspicious_time,json=maxSuspiciousTime,proto3" json:"max_suspicious_time,omitempty"`
	MaxIgnoreRounds            uint64                 `protobuf:"varint,12,opt,name=max_ignore_rounds,json=maxIgnoreRounds,proto3" json:"max_ignore_rounds,omitempty"`
	KDeepFinality              uint64                 `protobuf:"varint,13,opt,name=k_deep_finality,json=kDeepFinality,proto3" json:"k_deep_finality,omitempty"`
	MaxUnprovenTailBlocks      uint64                 `protobuf:"varint,14,opt,name=max_unproven_tail_blocks,json=maxUnprovenTailBlocks,proto3" json:"max_unproven_tail_blocks,omitempty"`
	MaxPeersPerSubnet          uint64                 `protobuf:"varint,15,opt,name=max_peers_per_subnet,json=maxPeersPerSubnet,proto3" json:"max_peers_per_subnet,omitempty"`
	DownHysteresisThreshold    uint64                 `protobuf:"varint,16,opt,name=down_hysteresis_threshold,json=downHysteresisThreshold,proto3" json:"down_hysteresis_threshold,omitempty"`
	MaxDownHysteresisThreshold uint64                 `protobuf:"varint,17,opt,name=max_down_hysteresis_threshold,json=maxDownHysteresisThreshold,proto3" json:"max_down_hysteresis_threshold,omitempty"`
	SuspiciousHysteresisWait   uint64                 `protobuf:"varint,18,opt,name=suspicious_hysteresis_wait,json=suspiciousHysteresisWait,proto3" json:"suspicious_hysteresis_wait,omitempty"`
	MaxSuspiciousForcedTxQueue uint64                 `protobuf:"varint,19,opt,name=max_suspicious_forced_tx_queue,json=maxSuspiciousForcedTxQueue,proto3" json:"max_suspicious_forced_tx_queue,omitempty"`
	MaxCensorshipRounds        uint64                 `protobuf:"varint,20,opt,name=max_censorship_rounds,json=maxCensorshipRounds,proto3" json:"max_censorship_rounds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GenesisParams) Reset() {
	*x = GenesisParams{}
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisParams) ProtoMessage() {}

func (x *GenesisParams) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisParams.ProtoReflect.Descriptor instead.
func (*GenesisParams) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisParams) GetSuspiciousThreshold() uint64 {
	if x != nil {
		return x.SuspiciousThreshold
	}
	return 0
}

func (x *GenesisParams) GetSovereignThreshold() uint64 {
	if x != nil {
		return x.SovereignThreshold
	}
	return 0
}

func (x *GenesisParams) GetDaThreshold() uint64 {
	if x != nil {
		return x.DaThreshold
	}
	return 0
}

func (x *GenesisParams) GetHysteresisWait() uint64 {
	if x != nil {
		return x.HysteresisWait
	}
	return 0
}

func (x *GenesisParams) GetMinPeers() uint64 {
	if x != nil {
		return x.MinPeers
	}
	return 0
}

func (x *GenesisParams) GetMinSubnetDiversity() uint64 {
	if x != nil {
		return x.MinSubnetDiversity
	}
	return 0
}

func (x *GenesisParams) GetMinAnchorPeers() uint64 {
	if x != nil {
		return x.MinAnchorPeers
	}
	return 0
}

func (x *GenesisParams) GetMaxChurnRate() uint64 {
	if x != nil {
		return x.MaxChurnRate
	}
	return 0
}

func (x *GenesisParams) GetMinAvgTenure() uint64 {
	if x != nil {
		return x.MinAvgTenure
	}
	return 0
}

func (x *GenesisParams) GetMaxPeerLatency() uint64 {
	if x != nil {
		return x.MaxPeerLatency
	}
	return 0
}

func (x *GenesisParams) GetMaxSuspiciousTime() uint64 {
	if x != nil {
		return x.MaxSuspiciousTime
	}
	return 0
}

func (x *GenesisParams) GetMaxIgnoreRounds() uint64 {
	if x != nil {
		return x.MaxIgnoreRounds
	}
	return 0
}

func (x *GenesisParams) GetKDeepFinality() uint64 {
	if x != nil {
		return x.KDeepFinality
	}
	return 0
}

func (x *GenesisParams) GetMaxUnprovenTailBlocks() uint64 {
	if x != nil {
		return x.MaxUnprovenTailBlocks
	}
	return 0
}

func (x *GenesisParams) GetMaxPeersPerSubnet() uint64 {
	if x != nil {
		return x.MaxPeersPerSubnet
	}
	return 0
}

func (x *GenesisParams) GetDownHysteresisThreshold() uint64 {
	if x != nil {
		return x.DownHysteresisThreshold
	}
	return 0
}

func (x *GenesisParams) GetMaxDownHysteresisThreshold() uint64 {
	if x != nil {
		return x.MaxDownHysteresisThreshold
	}
	return 0
}

func (x *GenesisParams) GetSuspiciousHysteresisWait() uint64 {
	if x != nil {
		return x.SuspiciousHysteresisWait
	}
	return 0
}

func (x *GenesisParams) GetMaxSuspiciousForcedTxQueue() uint64 {
	if x != nil {
		return x.MaxSuspiciousForcedTxQueue
	}
	return 0
}

func (x *GenesisParams) GetMaxCensorshipRounds() uint64 {
	if x != nil {
		return x.MaxCensorshipRounds
	}
	return 0
}

var File_engram_sovereignty_v1_genesis_proto protoreflect.FileDescriptor

const file_engram_sovereignty_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"#engram/sovereignty/v1/genesis.proto\x12\x15engram.sovereignty.v1\x1a!engram/sovereignty/v1/state.proto\"\x8d\x04\n" +
	"\fGenesisState\x12\x1b\n" +
	"\tfsm_state\x18\x01 \x01(\tR\bfsmState\x12.\n" +
	"\x13safe_blocks_counter\x18\x02 \x01(\x04R\x11safeBlocksCounter\x12/\n" +
	"\x13suspicious_duration\x18\x03 \x01(\x04R\x12suspiciousDuration\x126\n" +
	"\x17reanchoring_proof_valid\x18\x04 \x01(\bR\x15reanchoringProofValid\x12Q\n" +
	"\x0finitial_metrics\x18\x06 \x01(\v2(.engram.sovereignty.v1.PeripheralMetricsR\x0einitialMetrics\x12<\n" +
	"\x06params\x18\a \x01(\v2$.engram.sovereignty.v1.GenesisParamsR\x06params\x12)\n" +
	"\x10unhealthy_streak\x18\b \x01(\x04R\x0funhealthyStreak\x128\n" +
	"\x18failed_recovery_attempts\x18\t \x01(\x04R\x16failedRecoveryAttempts\x124\n" +
	"\x16suspicious_safe_blocks\x18\n" +
	" \x01(\x04R\x14suspiciousSafeBlocksJ\x04\b\x05\x10\x06R\x15hysteresis_wait_limit\"\xd1\a\n" +
	"\rGenesisParams\x121\n" +
	"\x14suspicious_threshold\x18\x01 \x01(\x04R\x13suspiciousThreshold\x12/\n" +
	"\x13sovereign_threshold\x18\x02 \x01(\x04R\x12sovereignThreshold\x12!\n" +
	"\fda_threshold\x18\x03 \x01(\x04R\vdaThreshold\x12'\n" +
	"\x0fhysteresis_wait\x18\x04 \x01(\x04R\x0ehysteresisWait\x12\x1b\n" +
	"\tmin_peers\x18\x05 \x01(\x04R\bminPeers\x120\n" +
	"\x14min_subnet_diversity\x18\x06 \x01(\x04R\x12minSubnetDiversity\x12(\n" +
	"\x10min_anchor_peers\x18\a \x01(\x04R\x0eminAnchorPeers\x12$\n" +
	"\x0emax_churn_rate\x18\b \x01(\x04R\fmaxChurnRate\x12$\n" +
	"\x0emin_avg_tenure\x18\t \x01(\x04R\fminAvgTenure\x12(\n" +
	"\x10max_peer_latency\x18\n" +
	" \x01(\x04R\x0emaxPeerLatency\x12.\n" +
	"\x13max_suspicious_time\x18\v \x01(\x04R\x11maxSuspiciousTime\x12*\n" +
	"\x11max_ignore_rounds\x18\f \x01(\x04R\x0fmaxIgnoreRounds\x12&\n" +
	"\x0fk_deep_finality\x18\r \x01(\x04R\rkDeepFinality\x127\n" +
	"\x18max_unproven_tail_blocks\x18\x0e \x01(\x04R\x15maxUnprovenTailBlocks\x12/\n" +
	"\x14max_peers_per_subnet\x18\x0f \x01(\x04R\x11maxPeersPerSubnet\x12:\n" +
	"\x19down_hysteresis_threshold\x18\x10 \x01(\x04R\x17downHysteresisThreshold\x12A\n" +
	"\x1dmax_down_hysteresis_threshold\x18\x11 \x01(\x04R\x1amaxDownHysteresisThreshold\x12<\n" +
	"\x1asuspicious_hysteresis_wait\x18\x12 \x01(\x04R\x18suspiciousHysteresisWait\x12B\n" +
	"\x1emax_suspicious_forced_tx_queue\x18\x13 \x01(\x04R\x1amaxSuspiciousForcedTxQueue\x122\n" +
	"\x15max_censorship_rounds\x18\x14 \x01(\x04R\x13maxCensorshipRoundsBCZAgithub.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/typesb\x06proto3"

var (
	file_engram_sovereignty_v1_genesis_proto_rawDescOnce sync.Once
	file_engram_sovereignty_v1_genesis_proto_rawDescData []byte
)

func file_engram_sovereignty_v1_genesis_proto_rawDescGZIP() []byte {
	file_engram_sovereignty_v1_genesis_proto_rawDescOnce.Do(func() {
		file_engram_sovereignty_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_genesis_proto_rawDesc), len(file_engram_sovereignty_v1_genesis_proto_rawDesc)))
	})
	return file_engram_sovereignty_v1_genesis_proto_rawDescData
}

var file_engram_sovereignty_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_engram_sovereignty_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil),      // 0: engram.sovereignty.v1.GenesisState
	(*GenesisParams)(nil),     // 1: engram.sovereignty.v1.GenesisParams
	(*PeripheralMetrics)(nil), // 2: engram.sovereignty.v1.PeripheralMetrics
}
var file_engram_sovereignty_v1_genesis_proto_depIdxs = []int32{
	2, // 0: engram.sovereignty.v1.GenesisState.initial_metrics:type_name -> engram.sovereignty.v1.PeripheralMetrics
	1, // 1: engram.sovereignty.v1.GenesisState.params:type_name -> engram.sovereignty.v1.GenesisParams
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engram_sovereignty_v1_genesis_proto_init() }
func file_engram_sovereignty_v1_genesis_proto_init() {
	if File_engram_sovereignty_v1_genesis_proto != nil {
		return
	}
	file_engram_sovereignty_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_genesis_proto_rawDesc), len(file_engram_sovereignty_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engram_sovereignty_v1_genesis_proto_goTypes,
		DependencyIndexes: file_engram_sovereignty_v1_genesis_proto_depIdxs,
		MessageInfos:      file_engram_sovereignty_v1_genesis_proto_msgTypes,
	}.Build()
	File_engram_sovereignty_v1_genesis_proto = out.File
	file_engram_sovereignty_v1_genesis_proto_goTypes = nil
	file_engram_sovereignty_v1_genesis_proto_depIdxs = nil
}
