// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engram/sovereignty/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateRequest) Reset() {
	*x = QueryStateRequest{}
	mi := &file_engram_sovereignty_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateRequest) ProtoMessage() {}

func (x *QueryStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateRequest.ProtoReflect.Descriptor instead.
func (*QueryStateRequest) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryStateResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FsmState              string                 `protobuf:"bytes,1,opt,name=fsm_state,json=fsmState,proto3" json:"fsm_state,omitempty"`
	SafeBlocks            uint64                 `protobuf:"varint,2,opt,name=safe_blocks,json=safeBlocks,proto3" json:"safe_blocks,omitempty"`
	SuspiciousDuration    uint64                 `protobuf:"varint,3,opt,name=suspicious_duration,json=suspiciousDuration,proto3" json:"suspicious_duration,omitempty"`
	ReanchoringProofValid bool                   `protobuf:"varint,4,opt,name=reanchoring_proof_valid,json=reanchoringProofValid,proto3" json:"reanchoring_proof_valid,omitempty"`
	Metrics               *PeripheralMetrics     `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueryStateResponse) Reset() {
	*x = QueryStateResponse{}
	mi := &file_engram_sovereignty_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateResponse) ProtoMessage() {}

func (x *QueryStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateResponse.ProtoReflect.Descriptor instead.
func (*QueryStateResponse) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStateResponse) GetFsmState() string {
	if x != nil {
		return x.FsmState
	}
	return ""
}

func (x *QueryStateResponse) GetSafeBlocks() uint64 {
	if x != nil {
		return x.SafeBlocks
	}
	return 0
}

func (x *QueryStateResponse) GetSuspiciousDuration() uint64 {
	if x != nil {
		return x.SuspiciousDuration
	}
	return 0
}

func (x *QueryStateResponse) GetReanchoringProofValid() bool {
	if x != nil {
		return x.ReanchoringProofValid
	}
	return false
}

func (x *QueryStateResponse) GetMetrics() *PeripheralMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_engram_sovereignty_v1_query_proto protoreflect.FileDescriptor

const file_engram_sovereignty_v1_query_proto_rawDesc = "" +
	"\n" +
	"!engram/sovereignty/v1/query.proto\x12\x15engram.sovereignty.v1\x1a!engram/sovereignty/v1/state.proto\"\x13\n" +
	"\x11QueryStateRequest\"\xff\x01\n" +
	"\x12QueryStateResponse\x12\x1b\n" +
	"\tfsm_state\x18\x01 \x01(\tR\bfsmState\x12\x1f\n" +
	"\vsafe_blocks\x18\x02 \x01(\x04R\n" +
	"safeBlocks\x12/\n" +
	"\x13suspicious_duration\x18\x03 \x01(\x04R\x12suspiciousDuration\x126\n" +
	"\x17reanchoring_proof_valid\x18\x04 \x01(\bR\x15reanchoringProofValid\x12B\n" +
	"\ametrics\x18\x05 \x01(\v2(.engram.sovereignty.v1.PeripheralMetricsR\ametrics2e\n" +
	"\x05Query\x12\\\n" +
	"\x05State\x12(.engram.sovereignty.v1.QueryStateRequest\x1a).engram.sovereignty.v1.QueryStateResponseBCZAgithub.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/typesb\x06proto3"

var (
	file_engram_sovereignty_v1_query_proto_rawDescOnce sync.Once
	file_engram_sovereignty_v1_query_proto_rawDescData []byte
)

func file_engram_sovereignty_v1_query_proto_rawDescGZIP() []byte {
	file_engram_sovereignty_v1_query_proto_rawDescOnce.Do(func() {
		file_engram_sovereignty_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_query_proto_rawDesc), len(file_engram_sovereignty_v1_query_proto_rawDesc)))
	})
	return file_engram_sovereignty_v1_query_proto_rawDescData
}

var file_engram_sovereignty_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_engram_sovereignty_v1_query_proto_goTypes = []any{
	(*QueryStateRequest)(nil),  // 0: engram.sovereignty.v1.QueryStateRequest
	(*QueryStateResponse)(nil), // 1: engram.sovereignty.v1.QueryStateResponse
	(*PeripheralMetrics)(nil),  // 2: engram.sovereignty.v1.PeripheralMetrics
}
var file_engram_sovereignty_v1_query_proto_depIdxs = []int32{
	2, // 0: engram.sovereignty.v1.QueryStateResponse.metrics:type_name -> engram.sovereignty.v1.PeripheralMetrics
	0, // 1: engram.sovereignty.v1.Query.State:input_type -> engram.sovereignty.v1.QueryStateRequest
	1, // 2: engram.sovereignty.v1.Query.State:output_type -> engram.sovereignty.v1.QueryStateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engram_sovereignty_v1_query_proto_init() }
func file_engram_sovereignty_v1_query_proto_init() {
	if File_engram_sovereignty_v1_query_proto != nil {
		return
	}
	file_engram_sovereignty_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_query_proto_rawDesc), len(file_engram_sovereignty_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engram_sovereignty_v1_query_proto_goTypes,
		DependencyIndexes: file_engram_sovereignty_v1_query_proto_depIdxs,
		MessageInfos:      file_engram_sovereignty_v1_query_proto_msgTypes,
	}.Build()
	File_engram_sovereignty_v1_query_proto = out.File
	file_engram_sovereignty_v1_query_proto_goTypes = nil
	file_engram_sovereignty_v1_query_proto_depIdxs = nil
}
