// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engram/sovereignty/v1/state.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot ngoại vi thô, khớp 1:1 với các biến sensor trong spec/core/EngramFSM.tla
// (btc_gap, da_gap/is_das_failed/is_attestation_failed, 6 chỉ số P2P tri-interface
// profiler dùng bởi IsP2PQualityHealthy). Đây là struct được MsgInjectFault và
// PrepareProposal dùng trực tiếp -- không đổi tên field nếu không port lại toàn bộ
// x/sovereignty/types/predicates.go.
type PeripheralMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bitcoin settlement sensor.
	BtcGap uint64 `protobuf:"varint,1,opt,name=btc_gap,json=btcGap,proto3" json:"btc_gap,omitempty"`
	// Celestia DA sensor.
	DaGap               uint64 `protobuf:"varint,2,opt,name=da_gap,json=daGap,proto3" json:"da_gap,omitempty"`
	IsDasFailed         bool   `protobuf:"varint,3,opt,name=is_das_failed,json=isDasFailed,proto3" json:"is_das_failed,omitempty"`
	IsAttestationFailed bool   `protobuf:"varint,4,opt,name=is_attestation_failed,json=isAttestationFailed,proto3" json:"is_attestation_failed,omitempty"`
	// P2P tri-interface sensor.
	SubnetDiversity uint64 `protobuf:"varint,5,opt,name=subnet_diversity,json=subnetDiversity,proto3" json:"subnet_diversity,omitempty"`
	ActiveAnchors   uint64 `protobuf:"varint,6,opt,name=active_anchors,json=activeAnchors,proto3" json:"active_anchors,omitempty"`
	CleanPeers      uint64 `protobuf:"varint,7,opt,name=clean_peers,json=cleanPeers,proto3" json:"clean_peers,omitempty"`
	PeerChurnRate   uint64 `protobuf:"varint,8,opt,name=peer_churn_rate,json=peerChurnRate,proto3" json:"peer_churn_rate,omitempty"`
	AvgPeerTenure   uint64 `protobuf:"varint,9,opt,name=avg_peer_tenure,json=avgPeerTenure,proto3" json:"avg_peer_tenure,omitempty"`
	PeerLatency     uint64 `protobuf:"varint,10,opt,name=peer_latency,json=peerLatency,proto3" json:"peer_latency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeripheralMetrics) Reset() {
	*x = PeripheralMetrics{}
	mi := &file_engram_sovereignty_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeripheralMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeripheralMetrics) ProtoMessage() {}

func (x *PeripheralMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeripheralMetrics.ProtoReflect.Descriptor instead.
func (*PeripheralMetrics) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *PeripheralMetrics) GetBtcGap() uint64 {
	if x != nil {
		return x.BtcGap
	}
	return 0
}

func (x *PeripheralMetrics) GetDaGap() uint64 {
	if x != nil {
		return x.DaGap
	}
	return 0
}

func (x *PeripheralMetrics) GetIsDasFailed() bool {
	if x != nil {
		return x.IsDasFailed
	}
	return false
}

func (x *PeripheralMetrics) GetIsAttestationFailed() bool {
	if x != nil {
		return x.IsAttestationFailed
	}
	return false
}

func (x *PeripheralMetrics) GetSubnetDiversity() uint64 {
	if x != nil {
		return x.SubnetDiversity
	}
	return 0
}

func (x *PeripheralMetrics) GetActiveAnchors() uint64 {
	if x != nil {
		return x.ActiveAnchors
	}
	return 0
}

func (x *PeripheralMetrics) GetCleanPeers() uint64 {
	if x != nil {
		return x.CleanPeers
	}
	return 0
}

func (x *PeripheralMetrics) GetPeerChurnRate() uint64 {
	if x != nil {
		return x.PeerChurnRate
	}
	return 0
}

func (x *PeripheralMetrics) GetAvgPeerTenure() uint64 {
	if x != nil {
		return x.AvgPeerTenure
	}
	return 0
}

func (x *PeripheralMetrics) GetPeerLatency() uint64 {
	if x != nil {
		return x.PeerLatency
	}
	return 0
}

var File_engram_sovereignty_v1_state_proto protoreflect.FileDescriptor

const file_engram_sovereignty_v1_state_proto_rawDesc = "" +
	"\n" +
	"!engram/sovereignty/v1/state.proto\x12\x15engram.sovereignty.v1\"\x81\x03\n" +
	"\x11PeripheralMetrics\x12\x17\n" +
	"\abtc_gap\x18\x01 \x01(\x04R\x06btcGap\x12\x15\n" +
	"\x06da_gap\x18\x02 \x01(\x04R\x05daGap\x12\"\n" +
	"\ris_das_failed\x18\x03 \x01(\bR\visDasFailed\x122\n" +
	"\x15is_attestation_failed\x18\x04 \x01(\bR\x13isAttestationFailed\x12)\n" +
	"\x10subnet_diversity\x18\x05 \x01(\x04R\x0fsubnetDiversity\x12%\n" +
	"\x0eactive_anchors\x18\x06 \x01(\x04R\ractiveAnchors\x12\x1f\n" +
	"\vclean_peers\x18\a \x01(\x04R\n" +
	"cleanPeers\x12&\n" +
	"\x0fpeer_churn_rate\x18\b \x01(\x04R\rpeerChurnRate\x12&\n" +
	"\x0favg_peer_tenure\x18\t \x01(\x04R\ravgPeerTenure\x12!\n" +
	"\fpeer_latency\x18\n" +
	" \x01(\x04R\vpeerLatencyBCZAgithub.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/typesb\x06proto3"

var (
	file_engram_sovereignty_v1_state_proto_rawDescOnce sync.Once
	file_engram_sovereignty_v1_state_proto_rawDescData []byte
)

func file_engram_sovereignty_v1_state_proto_rawDescGZIP() []byte {
	file_engram_sovereignty_v1_state_proto_rawDescOnce.Do(func() {
		file_engram_sovereignty_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_state_proto_rawDesc), len(file_engram_sovereignty_v1_state_proto_rawDesc)))
	})
	return file_engram_sovereignty_v1_state_proto_rawDescData
}

var file_engram_sovereignty_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_engram_sovereignty_v1_state_proto_goTypes = []any{
	(*PeripheralMetrics)(nil), // 0: engram.sovereignty.v1.PeripheralMetrics
}
var file_engram_sovereignty_v1_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_engram_sovereignty_v1_state_proto_init() }
func file_engram_sovereignty_v1_state_proto_init() {
	if File_engram_sovereignty_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_state_proto_rawDesc), len(file_engram_sovereignty_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engram_sovereignty_v1_state_proto_goTypes,
		DependencyIndexes: file_engram_sovereignty_v1_state_proto_depIdxs,
		MessageInfos:      file_engram_sovereignty_v1_state_proto_msgTypes,
	}.Build()
	File_engram_sovereignty_v1_state_proto = out.File
	file_engram_sovereignty_v1_state_proto_goTypes = nil
	file_engram_sovereignty_v1_state_proto_depIdxs = nil
}
