// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engram/sovereignty/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgSubmitRecoveryProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`                           // Validator hoặc rpc node gửi chứng chỉ
	ZkProof       []byte                 `protobuf:"bytes,2,opt,name=zk_proof,json=zkProof,proto3" json:"zk_proof,omitempty"`                // Chuỗi byte thô của bằng chứng Noir ZK sinh ra ngoài chuỗi
	PublicInputs  []byte                 `protobuf:"bytes,3,opt,name=public_inputs,json=publicInputs,proto3" json:"public_inputs,omitempty"` // Public input đi kèm proof (da_receipt encode), dùng cho VerifyZKProof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitRecoveryProofRequest) Reset() {
	*x = MsgSubmitRecoveryProofRequest{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitRecoveryProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitRecoveryProofRequest) ProtoMessage() {}

func (x *MsgSubmitRecoveryProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitRecoveryProofRequest.ProtoReflect.Descriptor instead.
func (*MsgSubmitRecoveryProofRequest) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSubmitRecoveryProofRequest) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgSubmitRecoveryProofRequest) GetZkProof() []byte {
	if x != nil {
		return x.ZkProof
	}
	return nil
}

func (x *MsgSubmitRecoveryProofRequest) GetPublicInputs() []byte {
	if x != nil {
		return x.PublicInputs
	}
	return nil
}

type MsgSubmitRecoveryProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitRecoveryProofResponse) Reset() {
	*x = MsgSubmitRecoveryProofResponse{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitRecoveryProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitRecoveryProofResponse) ProtoMessage() {}

func (x *MsgSubmitRecoveryProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitRecoveryProofResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitRecoveryProofResponse) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{1}
}

type MsgInjectFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`                              // Tài khoản quản trị môi trường thử nghiệm
	FaultInputs   *PeripheralMetrics     `protobuf:"bytes,2,opt,name=fault_inputs,json=faultInputs,proto3" json:"fault_inputs,omitempty"` // Cấu hình thông số lỗi môi trường muốn ép chuỗi tuân theo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgInjectFaultRequest) Reset() {
	*x = MsgInjectFaultRequest{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgInjectFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInjectFaultRequest) ProtoMessage() {}

func (x *MsgInjectFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInjectFaultRequest.ProtoReflect.Descriptor instead.
func (*MsgInjectFaultRequest) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgInjectFaultRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgInjectFaultRequest) GetFaultInputs() *PeripheralMetrics {
	if x != nil {
		return x.FaultInputs
	}
	return nil
}

type MsgInjectFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgInjectFaultResponse) Reset() {
	*x = MsgInjectFaultResponse{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgInjectFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInjectFaultResponse) ProtoMessage() {}

func (x *MsgInjectFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInjectFaultResponse.ProtoReflect.Descriptor instead.
func (*MsgInjectFaultResponse) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{3}
}

type MsgSubmitForcedTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // Tài khoản gửi yêu cầu buộc bao gồm tx
	Tx            []byte                 `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`         // Nội dung thô của tx cần được buộc đưa vào block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitForcedTxRequest) Reset() {
	*x = MsgSubmitForcedTxRequest{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitForcedTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitForcedTxRequest) ProtoMessage() {}

func (x *MsgSubmitForcedTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitForcedTxRequest.ProtoReflect.Descriptor instead.
func (*MsgSubmitForcedTxRequest) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgSubmitForcedTxRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgSubmitForcedTxRequest) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

type MsgSubmitForcedTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitForcedTxResponse) Reset() {
	*x = MsgSubmitForcedTxResponse{}
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitForcedTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitForcedTxResponse) ProtoMessage() {}

func (x *MsgSubmitForcedTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_sovereignty_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitForcedTxResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitForcedTxResponse) Descriptor() ([]byte, []int) {
	return file_engram_sovereignty_v1_tx_proto_rawDescGZIP(), []int{5}
}

var File_engram_sovereignty_v1_tx_proto protoreflect.FileDescriptor

const file_engram_sovereignty_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1eengram/sovereignty/v1/tx.proto\x12\x15engram.sovereignty.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a!engram/sovereignty/v1/state.proto\"\x8d\x01\n" +
	"\x1dMsgSubmitRecoveryProofRequest\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x19\n" +
	"\bzk_proof\x18\x02 \x01(\fR\azkProof\x12#\n" +
	"\rpublic_inputs\x18\x03 \x01(\fR\fpublicInputs:\x0e\x82\xe7\xb0*\tauthority\" \n" +
	"\x1eMsgSubmitRecoveryProofResponse\"\x89\x01\n" +
	"\x15MsgInjectFaultRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12K\n" +
	"\ffault_inputs\x18\x02 \x01(\v2(.engram.sovereignty.v1.PeripheralMetricsR\vfaultInputs:\v\x82\xe7\xb0*\x06sender\"\x18\n" +
	"\x16MsgInjectFaultResponse\"O\n" +
	"\x18MsgSubmitForcedTxRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x0e\n" +
	"\x02tx\x18\x02 \x01(\fR\x02tx:\v\x82\xe7\xb0*\x06sender\"\x1b\n" +
	"\x19MsgSubmitForcedTxResponse2\xf2\x02\n" +
	"\x03Msg\x12\x82\x01\n" +
	"\x13SubmitRecoveryProof\x124.engram.sovereignty.v1.MsgSubmitRecoveryProofRequest\x1a5.engram.sovereignty.v1.MsgSubmitRecoveryProofResponse\x12j\n" +
	"\vInjectFault\x12,.engram.sovereignty.v1.MsgInjectFaultRequest\x1a-.engram.sovereignty.v1.MsgInjectFaultResponse\x12s\n" +
	"\x0eSubmitForcedTx\x12/.engram.sovereignty.v1.MsgSubmitForcedTxRequest\x1a0.engram.sovereignty.v1.MsgSubmitForcedTxResponse\x1a\x05\x80\xe7\xb0*\x01BCZAgithub.com/cuongct220020/engram-sovereign-fsm/x/sovereignty/typesb\x06proto3"

var (
	file_engram_sovereignty_v1_tx_proto_rawDescOnce sync.Once
	file_engram_sovereignty_v1_tx_proto_rawDescData []byte
)

func file_engram_sovereignty_v1_tx_proto_rawDescGZIP() []byte {
	file_engram_sovereignty_v1_tx_proto_rawDescOnce.Do(func() {
		file_engram_sovereignty_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_tx_proto_rawDesc), len(file_engram_sovereignty_v1_tx_proto_rawDesc)))
	})
	return file_engram_sovereignty_v1_tx_proto_rawDescData
}

var file_engram_sovereignty_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_engram_sovereignty_v1_tx_proto_goTypes = []any{
	(*MsgSubmitRecoveryProofRequest)(nil),  // 0: engram.sovereignty.v1.MsgSubmitRecoveryProofRequest
	(*MsgSubmitRecoveryProofResponse)(nil), // 1: engram.sovereignty.v1.MsgSubmitRecoveryProofResponse
	(*MsgInjectFaultRequest)(nil),          // 2: engram.sovereignty.v1.MsgInjectFaultRequest
	(*MsgInjectFaultResponse)(nil),         // 3: engram.sovereignty.v1.MsgInjectFaultResponse
	(*MsgSubmitForcedTxRequest)(nil),       // 4: engram.sovereignty.v1.MsgSubmitForcedTxRequest
	(*MsgSubmitForcedTxResponse)(nil),      // 5: engram.sovereignty.v1.MsgSubmitForcedTxResponse
	(*PeripheralMetrics)(nil),              // 6: engram.sovereignty.v1.PeripheralMetrics
}
var file_engram_sovereignty_v1_tx_proto_depIdxs = []int32{
	6, // 0: engram.sovereignty.v1.MsgInjectFaultRequest.fault_inputs:type_name -> engram.sovereignty.v1.PeripheralMetrics
	0, // 1: engram.sovereignty.v1.Msg.SubmitRecoveryProof:input_type -> engram.sovereignty.v1.MsgSubmitRecoveryProofRequest
	2, // 2: engram.sovereignty.v1.Msg.InjectFault:input_type -> engram.sovereignty.v1.MsgInjectFaultRequest
	4, // 3: engram.sovereignty.v1.Msg.SubmitForcedTx:input_type -> engram.sovereignty.v1.MsgSubmitForcedTxRequest
	1, // 4: engram.sovereignty.v1.Msg.SubmitRecoveryProof:output_type -> engram.sovereignty.v1.MsgSubmitRecoveryProofResponse
	3, // 5: engram.sovereignty.v1.Msg.InjectFault:output_type -> engram.sovereignty.v1.MsgInjectFaultResponse
	5, // 6: engram.sovereignty.v1.Msg.SubmitForcedTx:output_type -> engram.sovereignty.v1.MsgSubmitForcedTxResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engram_sovereignty_v1_tx_proto_init() }
func file_engram_sovereignty_v1_tx_proto_init() {
	if File_engram_sovereignty_v1_tx_proto != nil {
		return
	}
	file_engram_sovereignty_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_sovereignty_v1_tx_proto_rawDesc), len(file_engram_sovereignty_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engram_sovereignty_v1_tx_proto_goTypes,
		DependencyIndexes: file_engram_sovereignty_v1_tx_proto_depIdxs,
		MessageInfos:      file_engram_sovereignty_v1_tx_proto_msgTypes,
	}.Build()
	File_engram_sovereignty_v1_tx_proto = out.File
	file_engram_sovereignty_v1_tx_proto_goTypes = nil
	file_engram_sovereignty_v1_tx_proto_depIdxs = nil
}
