// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: engram/sovereignty/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_SubmitRecoveryProof_FullMethodName = "/engram.sovereignty.v1.Msg/SubmitRecoveryProof"
	Msg_InjectFault_FullMethodName         = "/engram.sovereignty.v1.Msg/InjectFault"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dịch vụ xử lý chữ ký giao dịch (Msg Server)
type MsgClient interface {
	// Giao dịch đẩy chứng chỉ ZK Proof phục hồi lên chuỗi (Phục vụ E8/E9)
	SubmitRecoveryProof(ctx context.Context, in *MsgSubmitRecoveryProofRequest, opts ...grpc.CallOption) (*MsgSubmitRecoveryProofResponse, error)
	// Mạch tiêm lỗi cục bộ định tính phục vụ kịch bản lỗi (Phục vụ E2-E7)
	InjectFault(ctx context.Context, in *MsgInjectFaultRequest, opts ...grpc.CallOption) (*MsgInjectFaultResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitRecoveryProof(ctx context.Context, in *MsgSubmitRecoveryProofRequest, opts ...grpc.CallOption) (*MsgSubmitRecoveryProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitRecoveryProofResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitRecoveryProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InjectFault(ctx context.Context, in *MsgInjectFaultRequest, opts ...grpc.CallOption) (*MsgInjectFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgInjectFaultResponse)
	err := c.cc.Invoke(ctx, Msg_InjectFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations should embed UnimplementedMsgServer
// for forward compatibility.
//
// Dịch vụ xử lý chữ ký giao dịch (Msg Server)
type MsgServer interface {
	// Giao dịch đẩy chứng chỉ ZK Proof phục hồi lên chuỗi (Phục vụ E8/E9)
	SubmitRecoveryProof(context.Context, *MsgSubmitRecoveryProofRequest) (*MsgSubmitRecoveryProofResponse, error)
	// Mạch tiêm lỗi cục bộ định tính phục vụ kịch bản lỗi (Phục vụ E2-E7)
	InjectFault(context.Context, *MsgInjectFaultRequest) (*MsgInjectFaultResponse, error)
}

// UnimplementedMsgServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) SubmitRecoveryProof(context.Context, *MsgSubmitRecoveryProofRequest) (*MsgSubmitRecoveryProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRecoveryProof not implemented")
}
func (UnimplementedMsgServer) InjectFault(context.Context, *MsgInjectFaultRequest) (*MsgInjectFaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectFault not implemented")
}
func (UnimplementedMsgServer) testEmbeddedByValue() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_SubmitRecoveryProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitRecoveryProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitRecoveryProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitRecoveryProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitRecoveryProof(ctx, req.(*MsgSubmitRecoveryProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InjectFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInjectFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InjectFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_InjectFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InjectFault(ctx, req.(*MsgInjectFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engram.sovereignty.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRecoveryProof",
			Handler:    _Msg_SubmitRecoveryProof_Handler,
		},
		{
			MethodName: "InjectFault",
			Handler:    _Msg_InjectFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engram/sovereignty/v1/tx.proto",
}
