name: Go Test CI

on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
  pull_request:

jobs:
  test:
    name: Run Unit & E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Run Tests
        run: go test -v -coverprofile=coverage.txt ./...
